tasks:
  - name: "update api files"
    file_glob: './src/google_drive/api/*.cr'
    changes:
      -
        name: 'Remove common method prefix "drive_[api_name]_"'
        pattern: 'drive_%{api_name}_'
        new_value: ''
      -
        name: 'Restore operation name'
        pattern: 'operation: "%{capitalized_api_name}Api.'
        new_value: 'operation: "%{capitalized_api_name}Api.drive_%{api_name}_'
      -
        name: "Update ::File to IO | String"
        pattern: ': ::File'
        new_value: ': IO | String'
  - name: 'Update all'
    file_glob: './src/google_drive/**/*.cr'
    changes:
      -
        name: 'Correct JSON::Any?'
        pattern: 'JSON::Any\?'
        new_value: 'JSON::Any?'
      -
        name: 'Correct JSONAny'
        pattern: 'JSONAny'
        new_value: 'JSON::Any'
      -
        name: 'Correct GoogleDrive::String'
        pattern: 'GoogleDrive::String'
        new_value: 'String'
      -
        name: 'Correct ::::'
        pattern: '::::'
        new_value: '::'
      -
        name: "Remove empty if blocks"
        pattern: '^\s+if _[^\s]+ = [^\s]+$\n^\s+end$'
        new_value: ''
        multi_line: true
      -
        name: "Remove empty unless blocks"
        pattern: '(^\s+unless [^\s]+ = [^\s]+$\n^\s+end$|^\s+unless [^\s]+$\n^\s+end$)'
        new_value: ''
        multi_line: true
