#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleDrive::FileContentHintsThumbnail
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleDrive::FileContentHintsThumbnail do
  describe "test an instance of FileContentHintsThumbnail" do
    it "should create an instance of FileContentHintsThumbnail" do
      # instance = GoogleDrive::FileContentHintsThumbnail.new
      # expect(instance).to be_instance_of(GoogleDrive::FileContentHintsThumbnail)
    end
  end

  describe "test attribute 'image'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'mime_type'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
