#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleDrive::LabelList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleDrive::LabelList do
  describe "test an instance of LabelList" do
    it "should create an instance of LabelList" do
      # instance = GoogleDrive::LabelList.new
      # (instance).should be_a(GoogleDrive::LabelList)
    end
  end

  describe "test attribute 'kind'" do
    it "should work" do
      # instance = GoogleDrive::LabelList.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'labels'" do
    it "should work" do
      # instance = GoogleDrive::LabelList.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'next_page_token'" do
    it "should work" do
      # instance = GoogleDrive::LabelList.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
