#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for GoogleDrive::ReplyList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GoogleDrive::ReplyList do
  describe "test an instance of ReplyList" do
    it "should create an instance of ReplyList" do
      # instance = GoogleDrive::ReplyList.new
      # expect(instance).to be_instance_of(GoogleDrive::ReplyList)
    end
  end

  describe "test attribute 'kind'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'next_page_token'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'replies'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
