#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleDrive
  # Representation of a shared drive.
  class Drive
    include JSON::Serializable

    # Optional properties
    @[JSON::Field(key: "backgroundImageFile", type: DriveBackgroundImageFile?, presence: true, ignore_serialize: background_image_file.nil? && !background_image_file_present?, emit_null: true)]
    property background_image_file : DriveBackgroundImageFile?
    @[JSON::Field(ignore: true)]
    property? background_image_file_present : Bool = false

    # A short-lived link to this shared drive's background image.
    @[JSON::Field(key: "backgroundImageLink", type: String?, presence: true, ignore_serialize: background_image_link.nil? && !background_image_link_present?, emit_null: true)]
    property background_image_link : String?
    @[JSON::Field(ignore: true)]
    property? background_image_link_present : Bool = false

    @[JSON::Field(key: "capabilities", type: DriveCapabilities?, presence: true, ignore_serialize: capabilities.nil? && !capabilities_present?, emit_null: true)]
    property capabilities : DriveCapabilities?
    @[JSON::Field(ignore: true)]
    property? capabilities_present : Bool = false

    # The color of this shared drive as an RGB hex string. It can only be set on a drive.drives.update request that does not set themeId.
    @[JSON::Field(key: "colorRgb", type: String?, presence: true, ignore_serialize: color_rgb.nil? && !color_rgb_present?, emit_null: true)]
    property color_rgb : String?
    @[JSON::Field(ignore: true)]
    property? color_rgb_present : Bool = false

    # The time at which the shared drive was created (RFC 3339 date-time).
    @[JSON::Field(key: "createdTime", type: Time?, converter: Time::RFC3339Converter, presence: true, ignore_serialize: created_time.nil? && !created_time_present?, emit_null: true)]
    property created_time : Time?
    @[JSON::Field(ignore: true)]
    property? created_time_present : Bool = false

    # Whether the shared drive is hidden from default view.
    @[JSON::Field(key: "hidden", type: Bool?, presence: true, ignore_serialize: hidden.nil? && !hidden_present?, emit_null: true)]
    property hidden : Bool?
    @[JSON::Field(ignore: true)]
    property? hidden_present : Bool = false

    # The ID of this shared drive which is also the ID of the top level folder of this shared drive.
    @[JSON::Field(key: "id", type: String?, presence: true, ignore_serialize: id.nil? && !id_present?, emit_null: true)]
    property id : String?
    @[JSON::Field(ignore: true)]
    property? id_present : Bool = false

    # Identifies what kind of resource this is. Value: the fixed string \"drive#drive\".
    @[JSON::Field(key: "kind", type: String?, default: "drive#drive", presence: true, ignore_serialize: kind.nil? && !kind_present?, emit_null: true)]
    property kind : String?
    @[JSON::Field(ignore: true)]
    property? kind_present : Bool = false

    # The name of this shared drive.
    @[JSON::Field(key: "name", type: String?, presence: true, ignore_serialize: name.nil? && !name_present?, emit_null: true)]
    property name : String?
    @[JSON::Field(ignore: true)]
    property? name_present : Bool = false

    @[JSON::Field(key: "restrictions", type: DriveRestrictions?, presence: true, ignore_serialize: restrictions.nil? && !restrictions_present?, emit_null: true)]
    property restrictions : DriveRestrictions?
    @[JSON::Field(ignore: true)]
    property? restrictions_present : Bool = false

    # The ID of the theme from which the background image and color will be set. The set of possible driveThemes can be retrieved from a drive.about.get response. When not specified on a drive.drives.create request, a random theme is chosen from which the background image and color are set. This is a write-only field; it can only be set on requests that don't set colorRgb or backgroundImageFile.
    @[JSON::Field(key: "themeId", type: String?, presence: true, ignore_serialize: theme_id.nil? && !theme_id_present?, emit_null: true)]
    property theme_id : String?
    @[JSON::Field(ignore: true)]
    property? theme_id_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(*, @background_image_file : DriveBackgroundImageFile? = nil, @background_image_link : String? = nil, @capabilities : DriveCapabilities? = nil, @color_rgb : String? = nil, @created_time : Time? = nil, @hidden : Bool? = nil, @id : String? = nil, @kind : String? = "drive#drive", @name : String? = nil, @restrictions : DriveRestrictions? = nil, @theme_id : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
        background_image_file == o.background_image_file &&
        background_image_link == o.background_image_link &&
        capabilities == o.capabilities &&
        color_rgb == o.color_rgb &&
        created_time == o.created_time &&
        hidden == o.hidden &&
        id == o.id &&
        kind == o.kind &&
        name == o.name &&
        restrictions == o.restrictions &&
        theme_id == o.theme_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [background_image_file, background_image_link, capabilities, color_rgb, created_time, hidden, id, kind, name, restrictions, theme_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if !attributes[self.class.attribute_map[key]]? && self.class.openapi_nullable.includes?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        ({} of String => String).tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = GoogleDrive.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {} of String => String
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.includes?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        ({} of String => String).tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
