#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleDrive
  # Representation of a label field.
  class LabelField
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # Only present if valueType is dateString. RFC 3339 formatted date: YYYY-MM-DD.
    @[JSON::Field(key: "dateString", type: Array(Time)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter date_string : Array(Time)? = nil

    # The identifier of this field.
    @[JSON::Field(key: "id", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter id : String? = nil

    # Only present if valueType is integer.
    @[JSON::Field(key: "integer", type: Array(String)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter integer : Array(String)? = nil

    # This is always drive#labelField.
    @[JSON::Field(key: "kind", type: String?, default: "drive#labelField", required: false, nullable: false, emit_null: false)]
    getter kind : String? = "drive#labelField"

    # Only present if valueType is selection.
    @[JSON::Field(key: "selection", type: Array(String)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter selection : Array(String)? = nil

    # Only present if valueType is text.
    @[JSON::Field(key: "text", type: Array(String)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter text : Array(String)? = nil

    # Only present if valueType is user.
    @[JSON::Field(key: "user", type: Array(GoogleDrive::User)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter user : Array(GoogleDrive::User)? = nil

    # The field type. While new values may be supported in the future, the following are currently allowed:   - dateString  - integer  - selection  - text  - user
    @[JSON::Field(key: "valueType", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter value_type : String? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @date_string : Array(Time)? = nil,
      @id : String? = nil,
      @integer : Array(String)? = nil,
      @kind : String? = "drive#labelField",
      @selection : Array(String)? = nil,
      @text : Array(String)? = nil,
      @user : Array(GoogleDrive::User)? = nil,
      @value_type : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_user = @user).nil?
        invalid_properties.concat(OpenApi::ContainerValidator.list_invalid_properties_for(key: "user", container: _user)) if _user.is_a?(Array)
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_user = @user).nil?
        return false if _user.is_a?(Array) && !OpenApi::ContainerValidator.valid?(container: _user)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] date_string Object to be assigned
    def date_string=(date_string : Array(Time)?)
      if date_string.nil?
        return @date_string = nil
      end
      _date_string = date_string.not_nil!
      @date_string = _date_string
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] id Object to be assigned
    def id=(id : String?)
      if id.nil?
        return @id = nil
      end
      _id = id.not_nil!
      @id = _id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] integer Object to be assigned
    def integer=(integer : Array(String)?)
      if integer.nil?
        return @integer = nil
      end
      _integer = integer.not_nil!
      @integer = _integer
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(kind : String?)
      if kind.nil?
        return @kind = nil
      end
      _kind = kind.not_nil!
      @kind = _kind
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] selection Object to be assigned
    def selection=(selection : Array(String)?)
      if selection.nil?
        return @selection = nil
      end
      _selection = selection.not_nil!
      @selection = _selection
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] text Object to be assigned
    def text=(text : Array(String)?)
      if text.nil?
        return @text = nil
      end
      _text = text.not_nil!
      @text = _text
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] user Object to be assigned
    def user=(user : Array(GoogleDrive::User)?)
      if user.nil?
        return @user = nil
      end
      _user = user.not_nil!
      OpenApi::ContainerValidator.validate(container: _user) if _user.is_a?(Array)
      @user = _user
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] value_type Object to be assigned
    def value_type=(value_type : String?)
      if value_type.nil?
        return @value_type = nil
      end
      _value_type = value_type.not_nil!
      @value_type = _value_type
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@date_string, @id, @integer, @kind, @selection, @text, @user, @value_type)
  end
end
