#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./label"

module GoogleDrive
  # Response to a ModifyLabels request. This contains only those labels which were added or updated by the request.
  class ModifyLabelsResponse
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # This is always drive#modifyLabelsResponse
    @[JSON::Field(key: "kind", type: String?, default: "drive#modifyLabelsResponse", required: false, nullable: false, emit_null: false)]
    getter kind : String? = "drive#modifyLabelsResponse"

    # The list of labels which were added or updated by the request.
    @[JSON::Field(key: "modifiedLabels", type: Array(GoogleDrive::Label)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter modified_labels : Array(GoogleDrive::Label)? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @kind : String? = "drive#modifyLabelsResponse",
      @modified_labels : Array(GoogleDrive::Label)? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_modified_labels = @modified_labels).nil?
        invalid_properties.concat(OpenApi::ContainerValidator.list_invalid_properties_for(key: "modified_labels", container: _modified_labels)) if _modified_labels.is_a?(Array)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_modified_labels = @modified_labels).nil?
        return false if _modified_labels.is_a?(Array) && !OpenApi::ContainerValidator.valid?(container: _modified_labels)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(new_value : String?)
      @kind = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] modified_labels Object to be assigned
    def modified_labels=(new_value : Array(GoogleDrive::Label)?)
      unless new_value.nil?
        OpenApi::ContainerValidator.validate(container: new_value) if new_value.is_a?(Array)
      end

      @modified_labels = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@kind, @modified_labels)
  end
end
