#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleDrive
  # A list of replies to a comment on a file.
  class ReplyList
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # Identifies what kind of resource this is. Value: the fixed string \"drive#replyList\".
    @[JSON::Field(key: "kind", type: String?, default: "drive#replyList", required: false, nullable: false, emit_null: false)]
    getter kind : String? = "drive#replyList"

    # The page token for the next page of replies. This will be absent if the end of the replies list has been reached. If the token is rejected for any reason, it should be discarded, and pagination should be restarted from the first page of results.
    @[JSON::Field(key: "nextPageToken", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter next_page_token : String? = nil

    # The list of replies. If nextPageToken is populated, then this list may be incomplete and an additional page of results should be fetched.
    @[JSON::Field(key: "replies", type: Array(GoogleDrive::Reply)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter replies : Array(GoogleDrive::Reply)? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @kind : String? = "drive#replyList",
      @next_page_token : String? = nil,
      @replies : Array(GoogleDrive::Reply)? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_replies = @replies).nil?
        invalid_properties.concat(OpenApi::ContainerValidator.list_invalid_properties_for(key: "replies", container: _replies)) if _replies.is_a?(Array)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_replies = @replies).nil?
        return false if _replies.is_a?(Array) && !OpenApi::ContainerValidator.valid?(container: _replies)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(new_value : String?)
      @kind = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] next_page_token Object to be assigned
    def next_page_token=(new_value : String?)
      @next_page_token = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] replies Object to be assigned
    def replies=(new_value : Array(GoogleDrive::Reply)?)
      unless new_value.nil?
        OpenApi::ContainerValidator.validate(container: new_value) if new_value.is_a?(Array)
      end

      @replies = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@kind, @next_page_token, @replies)
  end
end
