#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

require "./user"

module GoogleDrive
  # A reply to a comment on a file.
  class Reply
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    # The action the reply performed to the parent comment. Valid values are:   - resolve  - reopen
    @[JSON::Field(key: "action", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter action : String? = nil

    @[JSON::Field(key: "author", type: GoogleDrive::User?, default: nil, required: false, nullable: false, emit_null: false)]
    getter author : GoogleDrive::User? = nil

    # The plain text content of the reply. This field is used for setting the content, while htmlContent should be displayed. This is required on creates if no action is specified.
    @[JSON::Field(key: "content", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter content : String? = nil

    # The time at which the reply was created (RFC 3339 date-time).
    @[JSON::Field(key: "createdTime", type: Time?, default: nil, required: false, nullable: false, emit_null: false, converter: Time::RFC3339Converter)]
    getter created_time : Time? = nil

    # Whether the reply has been deleted. A deleted reply has no content.
    @[JSON::Field(key: "deleted", type: Bool?, default: nil, required: false, nullable: false, emit_null: false)]
    getter deleted : Bool? = nil

    # The content of the reply with HTML formatting.
    @[JSON::Field(key: "htmlContent", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter html_content : String? = nil

    # The ID of the reply.
    @[JSON::Field(key: "id", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter id : String? = nil

    # Identifies what kind of resource this is. Value: the fixed string \"drive#reply\".
    @[JSON::Field(key: "kind", type: String?, default: "drive#reply", required: false, nullable: false, emit_null: false)]
    getter kind : String? = "drive#reply"

    # The last time the reply was modified (RFC 3339 date-time).
    @[JSON::Field(key: "modifiedTime", type: Time?, default: nil, required: false, nullable: false, emit_null: false, converter: Time::RFC3339Converter)]
    getter modified_time : Time? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @action : String? = nil,
      @author : GoogleDrive::User? = nil,
      @content : String? = nil,
      @created_time : Time? = nil,
      @deleted : Bool? = nil,
      @html_content : String? = nil,
      @id : String? = nil,
      @kind : String? = "drive#reply",
      @modified_time : Time? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_author = @author).nil?
        invalid_properties.concat(_author.list_invalid_properties_for("author")) if _author.is_a?(OpenApi::Validatable)
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_author = @author).nil?
        return false if _author.is_a?(OpenApi::Validatable) && !_author.valid?
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] action Object to be assigned
    def action=(new_value : String?)
      @action = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] author Object to be assigned
    def author=(new_value : GoogleDrive::User?)
      unless new_value.nil?
        new_value.validate if new_value.is_a?(OpenApi::Validatable)
      end

      @author = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] content Object to be assigned
    def content=(new_value : String?)
      @content = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] created_time Object to be assigned
    def created_time=(new_value : Time?)
      @created_time = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] deleted Object to be assigned
    def deleted=(new_value : Bool?)
      @deleted = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] html_content Object to be assigned
    def html_content=(new_value : String?)
      @html_content = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] id Object to be assigned
    def id=(new_value : String?)
      @id = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(new_value : String?)
      @kind = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] modified_time Object to be assigned
    def modified_time=(new_value : Time?)
      @modified_time = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@action, @author, @content, @created_time, @deleted, @html_content, @id, @kind, @modified_time)
  end
end
