#  Drive API
#
# Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#
# The version of the OpenAPI document: v3
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module GoogleDrive
  @[JSON::Serializable::Options(emit_nulls: true)]
  class StartPageToken
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties
    # Identifies what kind of resource this is. Value: the fixed string \"drive#startPageToken\".
    @[JSON::Field(key: "kind", type: String?, default: "drive#startPageToken", presence: true, ignore_serialize: kind.nil? && !kind_present?)]
    property kind : String?

    @[JSON::Field(ignore: true)]
    property? kind_present : Bool = false

    # The starting page token for listing changes.
    @[JSON::Field(key: "startPageToken", type: String?, presence: true, ignore_serialize: start_page_token.nil? && !start_page_token_present?)]
    property start_page_token : String?

    @[JSON::Field(ignore: true)]
    property? start_page_token_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(*, @kind : String? = "drive#startPageToken", @start_page_token : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.same?(o)
      self.class == o.class &&
        kind == o.kind &&
        start_page_token == o.start_page_token
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [UInt64] Hash code
    def_hash(@kind, @start_page_token)
  end
end
